# Form implementation generated from reading ui file 'ui_files/save_window.ui'
#
# Created by: PyQt6 UI code generator 6.2.3
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(464, 160)
        self.formLayout_2 = QtWidgets.QFormLayout(Dialog)
        self.formLayout_2.setObjectName("formLayout_2")
        self.title_label = QtWidgets.QLabel(Dialog)
        self.title_label.setObjectName("title_label")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.title_label)
        self.device_name_box = QtWidgets.QFormLayout()
        self.device_name_box.setObjectName("device_name_box")
        self.device_name_label = QtWidgets.QLabel(Dialog)
        self.device_name_label.setObjectName("device_name_label")
        self.device_name_box.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.device_name_label)
        self.device_name_input = QtWidgets.QLineEdit(Dialog)
        self.device_name_input.setObjectName("device_name_input")
        self.device_name_box.setWidget(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.device_name_input)
        self.formLayout_2.setLayout(1, QtWidgets.QFormLayout.ItemRole.SpanningRole, self.device_name_box)
        self.port_check_box = QtWidgets.QCheckBox(Dialog)
        self.port_check_box.setObjectName("port_check_box")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.ItemRole.LabelRole, self.port_check_box)
        self.done_button = QtWidgets.QPushButton(Dialog)
        self.done_button.setObjectName("done_button")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.ItemRole.FieldRole, self.done_button)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Save Data"))
        self.title_label.setText(_translate("Dialog", "Save Data"))
        self.device_name_label.setText(_translate("Dialog", "Device Name:"))
        self.port_check_box.setText(_translate("Dialog", "Include Port Name and Location."))
        self.done_button.setText(_translate("Dialog", "Done"))


# if __name__ == "__main__":
#     import sys
#     app = QtWidgets.QApplication(sys.argv)
#     Dialog = QtWidgets.QDialog()
#     ui = Ui_Dialog()
#     ui.setupUi(Dialog)
#     Dialog.show()
#     sys.exit(app.exec())
