# Form implementation generated from reading ui file 'src/gui/ui_files/tabbed_main_communication_gui.ui'
#
# Created by: PyQt6 UI code generator 6.2.3
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(996, 659)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.serial_tab = QtWidgets.QWidget()
        self.serial_tab.setObjectName("serial_tab")
        self.gridLayout = QtWidgets.QGridLayout(self.serial_tab)
        self.gridLayout.setObjectName("gridLayout")
        self.tabWidget.addTab(self.serial_tab, "")
        self.ethernet_tab = QtWidgets.QWidget()
        self.ethernet_tab.setObjectName("ethernet_tab")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.ethernet_tab)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.tabWidget.addTab(self.ethernet_tab, "")
        self.verticalLayout.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 996, 27))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuDatabase = QtWidgets.QMenu(self.menubar)
        self.menuDatabase.setObjectName("menuDatabase")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.action_export_data = QtGui.QAction(MainWindow)
        self.action_export_data.setObjectName("action_export_data")
        self.action_load_data = QtGui.QAction(MainWindow)
        self.action_load_data.setObjectName("action_load_data")
        self.action_delete_data = QtGui.QAction(MainWindow)
        self.action_delete_data.setObjectName("action_delete_data")
        self.action_database_credentials = QtGui.QAction(MainWindow)
        self.action_database_credentials.setObjectName("action_database_credentials")
        self.menuFile.addAction(self.action_export_data)
        self.menuFile.addAction(self.action_load_data)
        self.menuFile.addAction(self.action_delete_data)
        self.menuDatabase.addAction(self.action_database_credentials)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuDatabase.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.serial_tab), _translate("MainWindow", "Serial"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.ethernet_tab), _translate("MainWindow", "Ethernet"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuDatabase.setTitle(_translate("MainWindow", "Database"))
        self.action_export_data.setText(_translate("MainWindow", "Export Data"))
        self.action_load_data.setText(_translate("MainWindow", "Load Data"))
        self.action_delete_data.setText(_translate("MainWindow", "Delete All Data"))
        self.action_database_credentials.setText(_translate("MainWindow", "Database Login Credentials"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
